### ISSUE TITLE
File Syncing for Otto

### ISSUE THREAD

**Issue by StrongMonkey** [gptscript-ai/knowledge#119]
We should support file syncing for Otto, this includes:

- Web scraping. The input should be url and it should scrape all the content from the website to destination directory.
- Notion. The input should be a list of page IDs.
- Onedrive. The input should be a list of driveItem IDs that could represent either files or folders. The specificed folders and documents will be synced down to destination folder.

How to select inputs(notion page IDs, document IDs) will likely be done in a different place, where it could be a UI/frontend that enables user to select pages/documents/folders in UI.

**Comment by iwilltry42** [comment]
AFAICT, this is done :+1:
